sudo: false

language: node_js

node_js:
  - "node"

os:
- linux
- osx

before_install:
  - git submodule update --init --recursive

branches:
  only:
    - travis_deploy_test
    - /v\d+\.\d+\.\d+(?:\-\d+)?/

deploy:
  provider: script
  script:
    - npm run prebuild
    - npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  on:
    branch: travis_deploy_test
    tags: true