language: node_js

node_js:
  - "node"

os:
- linux
- osx

before_install:
  - git submodule update --init --recursive
  - echo "upload=${PREBUILD_TOKEN}" > ~/.prebuildrc

script:
  - npm run prebuild
  - npm run prebuild:upload

branches:
  only:
    - add_prebuild_support
