sudo: false

language: node_js

node_js:
  - "node"

os:
- linux
- osx

before_install:
  - git submodule update --init --recursive

branches:
  only:
    - master

deploy:
  provider: script
  script:
    - npm run prebuild
    - npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  on:
    branch: master
    tags: true