language: node_js

node_js:
  - "node"

os:
- linux
- osx

before_install:
  - git submodule update --init --recursive

script:
  - npm run prebuild -- -r $PREBUILD_RUNTIME
  - npm run prebuild:upload -- -u $PREBUILD_TOKEN

env:
  - PREBUILD_RUNTIME=node
  - PREBUILD_RUNTIME=electron

branches:
  only:
    - add_prebuild_support
