environment:
  nodejs_version: "10"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - npm test

branches:
  only:
    - travis_deploy_test
    - /^v.*$/

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)
