environment:
  nodejs_version: "10"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - npm test

deploy_script:
  - npm run prebuild
  - npm run prebuild:upload -u %PREBUILD_UPLOAD%

branches:
  only:
    - travis_deploy_test
    - /^v.*$/

deploy:
  provider: Script
  on:
    appveyor_repo_tag: true