environment:
  nodejs_version: "10"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm install

build: off

deploy_script:
  - npm run prebuild
  - npm run prebuild:upload -u %PREBUILD_UPLOAD%

deploy:
  provider: Script
  on:
    APPVEYOR_REPO_TAG: true